DeSoMot/Models/ErrorViewModel.cs
namespace DeSoMot.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

DeSoMot/Models/NhanVien.cs
using System.ComponentModel.DataAnnotations;

namespace DeSoMot.Models
{
    public class NhanVien
    {
        [Key]
        public Guid Id { get; set; }
        public string Name { get; set; }
        public int Tuoi {  get; set; }
        public string GioiTinh {  get; set; }

        public PhongBan? PhongBan { get; set; }
        //? có hoặc k cũng đc
    }
}

DeSoMot/Models/PhongBan.cs
using System.ComponentModel.DataAnnotations;

namespace DeSoMot.Models
{
    public class PhongBan
    {
        [Key]
        public string MaPB { get; set; }
        public string Name { get; set; }

        //thể hiện 1 phòng ban có n nhân vien
        public List<NhanVien> NhanViens { get; set; }
    }
}

DeSoMot/Models/SinhVienDbContext.cs
using Microsoft.EntityFrameworkCore;

namespace DeSoMot.Models
{
    //đại diện cho sql ở trong visual
    public class SinhVienDbContext : DbContext
    {
        public SinhVienDbContext()
        {
        }

        //nếu dùng các add chuỗi kết nối trực tiếp ở đây thì thêm contructor k có tham số

        //contructor có tham số: ctrl + .
        public SinhVienDbContext(DbContextOptions options) : base(options)
        {
        }

        //db set : đạ-i diện cho 1 bảng
        public DbSet<NhanVien> NhanViens { get; set; }
        public DbSet<PhongBan> PhongBans { get; set; }

    }
}

DeSoMot/Controllers/HomeController.cs
using DeSoMot.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace DeSoMot.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

DeSoMot/Controllers/NhanVienController.cs
using DeSoMot.Models;
using Microsoft.AspNetCore.Mvc;

namespace DeSoMot.Controllers
{
    public class NhanVienController : Controller
    {
        //khoi tao lai db 
        SinhVienDbContext _db;
        public NhanVienController(SinhVienDbContext db)
        {
            _db = db;
        }
        [HttpGet]
        public IActionResult Index()
        {
            var nhanVienList = _db.NhanViens.ToList();
            return View(nhanVienList);
        }
        //theem 1 nhan vien
        public IActionResult Create() // chỉ dùng để tạo ra view daao diên crate
        { 
            return View();
        }
        [HttpPost]
        public IActionResult Create(NhanVien nv)
        {
            _db.NhanViens.Add(nv);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

DeSoMot/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

DeSoMot/Views/NhanVien/Create.cshtml
@model DeSoMot.Models.NhanVien

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>NhanVien</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Tuoi" class="control-label"></label>
                <input asp-for="Tuoi" class="form-control" />
                <span asp-validation-for="Tuoi" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GioiTinh" class="control-label"></label>
                <input asp-for="GioiTinh" class="form-control" />
                <span asp-validation-for="GioiTinh" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DeSoMot/Views/NhanVien/Index.cshtml
@model IEnumerable<DeSoMot.Models.NhanVien>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Tuoi)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.GioiTinh)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Tuoi)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.GioiTinh)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>

DeSoMot/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DeSoMot</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/DeSoMot.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DeSoMot</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="NhanVien" asp-action="Index">Nhân Viên</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - DeSoMot - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>